# Roubos de celular na cidade de São Paulo

Nesse notebook, vamos filtrar e tratar os dados de roubos de celulares ocorridos na cidade de São Paulo, utilizando Jupyter e GeoPandas

In [1]:
# Importando a biblioteca Pandas para leitura dos dados
import pandas as pd

In [2]:
# Lendo os dados
filename = 'data/dados_roubo_celular_sp_2024.xlsx'

df_roubos = pd.read_excel(filename)

In [3]:
df_roubos.head()

,ID_DELEGACIA,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,ANO_BO,NUM_BO,VERSAO,NOME_DEPARTAMENTO_CIRC,NOME_SECCIONAL_CIRC,...,DESCR_MODO_OBJETO,DESCR_TIPO_OBJETO,DESCR_SUBTIPO_OBJETO,DESCR_UNIDADE,QUANTIDADE_OBJETO,MARCA_OBJETO,FLAG_BLOQUEIO,FLAG_DESBLOQUEIO,MES,ANO
0,10109,DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,2024,AL6931,1,DECAP,DEL.SEC.1º CENTRO,...,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Samsung,N,N,1,2024
1,10109,DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,2024,AL6931,1,DECAP,DEL.SEC.1º CENTRO,...,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Samsung,N,N,1,2024
2,10109,DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,2024,AN9687,1,DECAP,DEL.SEC.1º CENTRO,...,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Outros,S,N,1,2024
3,10109,DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,2024,AH3601,2,DECAP,DEL.SEC.7º ITAQUERA,...,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Samsung,N,N,1,2024
4,10109,DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,2024,AH3601,2,DECAP,DEL.SEC.7º ITAQUERA,...,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Samsung,N,N,1,2024

In [4]:
# Mostrar todas as colunas para verificar se temos informações de latitude e longitude
df_roubos.columns

Index(['ID_DELEGACIA', 'NOME_DEPARTAMENTO', 'NOME_SECCIONAL', 'NOME_DELEGACIA',
       'NOME_MUNICIPIO', 'ANO_BO', 'NUM_BO', 'VERSAO',
       'NOME_DEPARTAMENTO_CIRC', 'NOME_SECCIONAL_CIRC', 'NOME_DELEGACIA_CIRC',
       'NOME_MUNICIPIO_CIRC', 'DATA_OCORRENCIA_BO', 'HORA_OCORRENCIA',
       'DESCRICAO_APRESENTACAO', 'DATAHORA_REGISTRO_BO', 'DATA_COMUNICACAO_BO',
       'DATAHORA_IMPRESSAO_BO', 'DESCR_PERIODO', 'AUTORIA_BO',
       'FLAG_INTOLERANCIA', 'TIPO_INTOLERANCIA', 'FLAG_FLAGRANTE',
       'FLAG_STATUS', 'DESC_LEI', 'FLAG_ATO_INFRACIONAL', 'RUBRICA',
       'DESCR_CONDUTA', 'DESDOBRAMENTO', 'CIRCUNSTANCIA', 'DESCR_TIPOLOCAL',
       'DESCR_SUBTIPOLOCAL', 'CIDADE', 'BAIRRO', 'CEP', 'LOGRADOURO_VERSAO',
       'LOGRADOURO', 'NUMERO_LOGRADOURO', 'LATITUDE', 'LONGITUDE',
       'CONT_OBJETO', 'DESCR_MODO_OBJETO', 'DESCR_TIPO_OBJETO',
       'DESCR_SUBTIPO_OBJETO', 'DESCR_UNIDADE', 'QUANTIDADE_OBJETO',
       'MARCA_OBJETO', 'FLAG_BLOQUEIO', 'FLAG_DESBLOQUEIO', 'MES', 'ANO'],
      dtype='object')

In [5]:
# Mostrar apenas os dados de latitude e longitude
df_roubos[['LATITUDE', 'LONGITUDE']]

         LATITUDE  LONGITUDE
0        0.000000   0.000000
1        0.000000   0.000000
2      -23.528590 -46.606265
3        0.000000   0.000000
4        0.000000   0.000000
...           ...        ...
111022 -23.488858 -46.375312
111023 -23.488858 -46.375312
111024 -23.488858 -46.375312
111025 -23.488858 -46.375312
111026 -23.488858 -46.375312

[111027 rows x 2 columns]

In [6]:
# Removendo valores zerados ou NaN
df_roubos = df_roubos.dropna(subset=['LATITUDE', 'LONGITUDE'])
df_roubos = df_roubos[(df_roubos['LATITUDE'] != 0) | (df_roubos['LONGITUDE'] != 0)]
df_roubos[['LATITUDE', 'LONGITUDE']]

         LATITUDE  LONGITUDE
2      -23.528590 -46.606265
9      -23.559632 -46.634949
10     -23.559632 -46.634949
11     -23.552427 -46.629118
12     -23.552063 -46.634225
...           ...        ...
111022 -23.488858 -46.375312
111023 -23.488858 -46.375312
111024 -23.488858 -46.375312
111025 -23.488858 -46.375312
111026 -23.488858 -46.375312

[92319 rows x 2 columns]

## Criando o GeoDataframe (GeoPandas)

In [7]:
# Importando a biblioteca Shapely
from shapely.geometry import Point

In [ ]:
# Criando a coluna geometry
df_roubos['geometry'] = None

for index, row in df_roubos.iterrows():
    df_roubos.loc[index, 'geometry'] = Point(row.LONGITUDE, row.LATITUDE)

In [ ]:
# Mostrando dos dados
df_roubos.head(5)

In [ ]:
# Verificando o tipo do dataframe
type(df_roubos)

In [ ]:
# Importando GeoPandas
import geopandas as gpd

In [ ]:
# Criando o GeoDataFrame
gdf_roubos = gpd.GeoDataFrame(df_roubos, geometry='geometry')

In [ ]:
# Verificando tipo
type(gdf_roubos)

In [ ]:
# Mostrar dados
gdf_roubos.head()

In [ ]:
# Mostrando os dados utilizando a função plot
gdf_roubos.plot()

## Operação de interseção entre geometrias

Aparentemente já temos um esboço dos nossos dados. Vamos carregar o nosso gdf da capital de São Paulo e mostrar os dois dados em um só mapa.

In [ ]:
# Carregando os dados da capital de SP
filename = 'data/capital_são_paulo.json'

gdf_capital_sp = gpd.read_file(filename, driver='GeoJSON')

In [ ]:
# Mostrando os dados carregados com a função plot
gdf_capital_sp.plot()

### Agora camos mostrar os dois conjuntos de dados utilizando o `matplotlib`

In [ ]:
# Importando o matplotlib
import matplotlib.pyplot as plt

In [ ]:
# Mostrando os dados com o matplotlib
fig, ax = plt.subplots(figsize=(15, 15))

gdf_roubos.plot(ax=ax)
gdf_capital_sp.plot(ax=ax, facecolor="None", edgecolor="black")

#### Podemos ver que há alguns pontos que fogem da região da capital, vamos agora filtrar esses dados para visualizarmos apenas os dados dentro da região da capital

In [ ]:
# Primeiramente, vamos pegar o polygon de SP
polygon_sp = gdf_capital_sp.iloc[0].geometry

In [ ]:
# Visualizar o polygon
polygon_sp

In [ ]:
# Fazer a operação de intersação entre as geometrias
gdf_roubos_capital = gdf_roubos[gdf_roubos.intersects(polygon_sp)]

Vamos mostrar novamente os dados em um mapa

In [ ]:
# Mostrando os dados filtrados com o matplotlib
fig, ax = plt.subplots(figsize=(10, 10))

gdf_roubos_capital.plot(ax=ax)
gdf_capital_sp.plot(ax=ax, facecolor="None", edgecolor="black")

### Agora que temos os dados filtrados, vamos salvar para usar posteriormente

In [ ]:
import datetime

# Itera sobre todas as colunas do GeoDataFrame
for col in gdf_roubos_capital.columns:
    # Verifica se os valores da coluna são do tipo datetime.time
    if isinstance(gdf_roubos_capital[col].dropna().iloc[0], datetime.time):
        # Converte os valores para string no formato 'HH:MM:SS'
        gdf_roubos_capital[col] = gdf_roubos_capital[col].apply(lambda x: x.strftime('%H:%M:%S') if pd.notnull(x) else None)

In [ ]:
# Salvando os dados de roubo em SP
filename = "data/roubo_celular_capital.json"

gdf_roubos_capital.to_file(filename, driver='GeoJSON')